jobs:
  build:
    docker:
      - image: circleci/node:10.15.0
    steps:
      - checkout
      - setup_remote_docker
      - run: |
          TAG=0.1.$CIRCLE_BUILD_NUM
          docker build -t jeverd/liteboard-express .
          echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin  # (4)
          docker push jeverd/liteboard-express
      - run: |
          TAG=0.1.$CIRCLE_BUILD_NUM
          cd docker
          ls
          docker build -t jeverd/liteboard-ngnix .
          echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin  # (4)
          docker push jeverd/liteboard-ngnix 
  tests:
    docker:
      - image: circleci/node:10.15.0
      - image: redis
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: 'Running tests'
          command: |
            echo 'running npm install'
            npm install
            cd config
            mv example.env .env
            echo 'now running tests'
            cd ..
            npm test

workflows:
  version: 2
  main:
    jobs:
      - build:
          filters:
            branches:
              only: 
                - dev
                - dockerUPdate
                - janusAws
      - tests
          
