version: 2
jobs:
  build:
    branches:
    only:
      - master
    docker:
      - image: alpine
    steps:
      - checkout
      - setup_remote_docker
      - run: |
          TAG=0.1.$CIRCLE_BUILD_NUM
          cd server
          docker build -t jeverd/liteboard-express .
          echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin  # (4)
          docker push jeverd/liteboard-express
      - run: |
          TAG=0.1.$CIRCLE_BUILD_NUM
          cd docker
          docker build -t jeverd/liteboard-ngnix .
          echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin  # (4)
          docker push jeverd/liteboard-ngnix
          
      # - run:
      #     name: 'Deploy to AWS EC2 INSTANACE'
      #     command: |
      #       echo 'Deploying to EC2'
      #       echo 'ec2-35-183-20-250.ca-central-1.compute.amazonaws.com' >> ~/.ssh/known_hosts
      #       ssh -o StrictHostKeyChecking=no ec2-user@ec2-35-183-20-250.ca-central-1.compute.amazonaws.com "./deploy.sh"
        